from bgpview_controller import bgpviewController

controller = bgpviewController()
print(controller.get_asn_details(65132))
print(controller.get_ip_prefix('8.8.8.0/24'))

""" Output:
{'abuse_contacts': ['abuse@iana.org'],
 'asn': 65132,
 'country_code': None,
 'date_updated': None,
 'description_full': 'Reserved for Private Use [RFC6996]',
 'description_short': 'Reserved for Private Use [RFC6996]',
 'email_contacts': ['iana@iana.org'],
 'iana_assignment': {'assignment_status': 'reserved',
                     'date_assigned': None,
                     'description': 'Reserved for Private Use [RFC6996]',
                     'whois_server': 'whois.iana.org'},
 'looking_glass': None,
 'name': 'IANA-RESERVED',
 'owner_address': ['Internet Assigned Numbers Authority',
                   '12025 Waterfront Drive, Suite 300',
                   'Los Angeles CA 90094',
                   'USA'],
 'rir_allocation': {'allocation_status': 'reserved',
                    'country_code': None,
                    'date_allocated': None,
                    'rir_name': None},
 'traffic_estimation': None,
 'traffic_ratio': None,
 'website': None}
{'abuse_contacts': ['network-abuse@google.com'],
 'asns': [{'asn': 15169,
           'country_code': 'US',
           'description': 'Google LLC',
           'name': 'GOOGLE',
           'prefix_upstreams': [{'asn': 701,
                                 'country_code': 'US',
                                 'description': 'MCI Communications Services, '
                                                'Inc. d/b/a Verizon Business',
                                 'name': 'UUNET'},
                                {'asn': 6453,
                                 'country_code': 'US',
                                 'description': 'TATA COMMUNICATIONS (AMERICA) '
                                                'INC',
                                 'name': 'AS6453'},
                                {'asn': 3491,
                                 'country_code': 'US',
                                 'description': 'PCCW Global, Inc.',
                                 'name': 'BTN-ASN'},
                                {'asn': 1299,
                                 'country_code': 'EU',
                                 'description': 'Telia Carrier',
                                 'name': 'TELIANET'},
                                {'asn': 2497,
                                 'country_code': 'JP',
                                 'description': 'Internet Initiative Japan '
                                                'Inc.',
                                 'name': 'IIJ'},
                                {'asn': 3257,
                                 'country_code': 'DE',
                                 'description': 'GTT',
                                 'name': 'GTT-BACKBONE'},
                                {'asn': 7018,
                                 'country_code': 'US',
                                 'description': 'AT&T Services, Inc.',
                                 'name': 'ATT-INTERNET4'},
                                {'asn': 2914,
                                 'country_code': 'US',
                                 'description': 'NTT America, Inc.',
                                 'name': 'NTT-COMMUNICATIONS-2914'},
                                {'asn': 3356,
                                 'country_code': 'US',
                                 'description': 'Level 3 Parent, LLC',
                                 'name': 'LEVEL3'},
                                {'asn': 1239,
                                 'country_code': 'US',
                                 'description': 'Sprint',
                                 'name': 'SPRINTLINK'},
                                {'asn': 6762,
                                 'country_code': 'IT',
                                 'description': 'TELECOM ITALIA SPARKLE S.p.A.',
                                 'name': 'SEABONE-NET'},
                                {'asn': 209,
                                 'country_code': 'US',
                                 'description': 'CenturyLink Communications, '
                                                'LLC',
                                 'name': 'CENTURYLINK-US-LEGACY-QWEST'}]}],
 'cidr': 24,
 'country_codes': {'maxmind_country_code': 'US',
                   'rir_allocation_country_code': 'US',
                   'whois_country_code': 'US'},
 'date_updated': '2019-09-03 21:45:36',
 'description_full': ['Google LLC'],
 'description_short': 'Google LLC',
 'email_contacts': ['network-abuse@google.com', 'arin-contact@google.com'],
 'iana_assignment': {'assignment_status': 'assigned',
                     'date_assigned': None,
                     'description': 'Assigned by ARIN',
                     'whois_server': 'whois.arin.net'},
 'ip': '8.8.8.0',
 'maxmind': {'city': None, 'country_code': 'US'},
 'name': 'LVLT-GOGL-8-8-8',
 'owner_address': ['1600 Amphitheatre Parkway',
                   'Mountain View',
                   'CA',
                   '94043',
                   'US'],
 'prefix': '8.8.8.0/24',
 'related_prefixes': [],
 'rir_allocation': {'allocation_status': 'allocated',
                    'cidr': 9,
                    'country_code': 'US',
                    'date_allocated': '1992-12-01 00:00:00',
                    'ip': '8.0.0.0',
                    'prefix': '8.0.0.0/9',
                    'rir_name': 'ARIN'}}
"""